### ISSUE TITLE
Trailing Spaces In Decrypted Message

### ISSUE THREAD

**Issue by ignabelitzky** [farukalpay/TextEncryptionWithLinearAlgebra#1]
Hi, how are you?

When I execute the program, the decrypted message prints into the console with the trailing spaces of the algorithm.

My solution was to create a function inside an anonymous namespace to remove the trailing spaces from the decrypted vector of ints. I call that function just before the return of **decrypted_message** inside the method **decrypt**.

Here is the function and where I call it:
![image](https://github.com/farukalpay/TextEncryptionWithLinearAlgebra/assets/13757390/37c47a1b-8161-447a-a0f7-2f5d660d0522)
![image](https://github.com/farukalpay/TextEncryptionWithLinearAlgebra/assets/13757390/ac789ea6-90f7-422f-a829-04f4d2aa9467)

I will open a Pull Request with the solution so you can check it out.

Best regards,
Ignacio

**Comment by farukalpay** [comment]
Approved your pull request, thanks :)
